import type { MatchState, SportCode } from "@shared/sports";
import { MatchCard, MatchCardSkeleton, FavoriteEmpty } from "@/components/sports/MatchCard";
import { FeedEmpty, FeedError } from "@/components/sports/ViewStates";
import { SportsAppLayout } from "@/components/SportsAppLayout";
import { useFavoriteMatches } from "@/hooks/useFavoriteMatches";
import { trpc } from "@/lib/trpc";
import { CalendarDays, ChevronRight, Flame, Search, Star, Trophy, Zap } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

type SportFilter = "all" | SportCode;
const sports: Array<{ id: SportFilter; label: string; glyph: string }> = [{ id: "all", label: "All sports", glyph: "✦" }, { id: "football", label: "Football", glyph: "FT" }, { id: "basketball", label: "Basketball", glyph: "BK" }, { id: "tennis", label: "Tennis", glyph: "TN" }, { id: "cricket", label: "Cricket", glyph: "CR" }, { id: "rugby", label: "Rugby", glyph: "RG" }, { id: "ice-hockey", label: "Ice hockey", glyph: "IH" }, { id: "volleyball", label: "Volleyball", glyph: "VB" }];
const stateTabs: Array<{ id: MatchState; label: string }> = [{ id: "live", label: "Live now" }, { id: "upcoming", label: "Next up" }, { id: "finished", label: "Final" }];

export default function Home() {
  const [state, setState] = useState<MatchState>("live");
  const [sport, setSport] = useState<SportFilter>("all");
  const [search, setSearch] = useState("");
  const { favoriteIds, isReady, toggleFavorite } = useFavoriteMatches();
  const hasSearch = Boolean(search.trim());
  const feedInput = useMemo(() => ({ state: hasSearch ? undefined : state, sport: sport === "all" ? undefined : sport, search: search.trim() || undefined }), [hasSearch, state, sport, search]);
  const feed = trpc.sports.feed.useQuery(feedInput, { refetchInterval: 45_000, refetchIntervalInBackground: false, staleTime: 20_000 });
  const favoriteMatches = useMemo(() => (feed.data?.matches ?? []).filter((match) => favoriteIds.includes(match.id)), [feed.data?.matches, favoriteIds]);
  const liveCount = (feed.data?.matches ?? []).filter((match) => match.status === "live").length;
  const pageLabel = hasSearch ? "search" : state === "live" ? "live" : state === "upcoming" ? "upcoming" : "final";

  return <SportsAppLayout onSearch={setSearch} searchValue={search}><main className="mx-auto w-full max-w-7xl px-4 pb-12 pt-6 sm:px-6 lg:px-8">
    <section className="nb-shadow-lg relative overflow-hidden border-[3px] border-[#151515] bg-[#1857f6] px-5 py-7 text-white sm:px-8"><div className="absolute -right-10 -top-10 h-44 w-44 rotate-12 border-[16px] border-[#ffe24a]" /><div className="absolute bottom-0 left-0 h-4 w-full bg-[repeating-linear-gradient(45deg,#151515_0_12px,#ffe24a_12px_24px)]" /><div className="relative flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><div className="mb-2 inline-flex items-center gap-2 border-2 border-[#151515] bg-[#ffe24a] px-2 py-1 text-[10px] font-black uppercase tracking-[.16em] text-[#151515]"><span className="h-2 w-2 animate-pulse bg-[#e8462f]" />Live signal</div><h1 className="display text-5xl font-black uppercase leading-[.82] sm:text-7xl">Every match.<br /><span className="text-[#ffe24a]">No mute button.</span></h1><p className="mt-4 max-w-lg text-sm font-bold leading-6 text-[#eaf0ff]">The loudest multi-sport score board on the internet. Follow the swings, shocks, and scores in one place.</p></div><div className="flex shrink-0 items-center gap-3 border-[3px] border-[#151515] bg-[#ff6b4a] p-3 shadow-[5px_5px_0_#151515]"><span className="grid h-11 w-11 place-items-center border-2 border-[#151515] bg-[#ffe24a] text-[#151515]"><Flame size={22} strokeWidth={3} /></span><span><span className="display block text-4xl font-black leading-none">{liveCount.toString().padStart(2, "0")}</span><span className="mt-1 block text-[10px] font-black uppercase tracking-[.14em]">Games live</span></span></div></div></section>

    <section className="mt-6 border-[3px] border-[#151515] bg-[#ffe24a] p-3 shadow-[5px_5px_0_#151515]"><div className="mb-2 flex items-center gap-2"><Star size={15} strokeWidth={3} fill="currentColor" /><h2 className="text-[11px] font-black uppercase tracking-[.15em]">Pinned matches</h2>{favoriteMatches.length > 0 && <span className="border border-[#151515] bg-white px-1.5 py-0.5 text-[10px] font-black">{favoriteMatches.length}</span>}</div><div className="scrollbar-none flex gap-3 overflow-x-auto pb-0.5">{!isReady || feed.isLoading ? <><div className="nb-skeleton h-[112px] min-w-[268px]" /><div className="nb-skeleton hidden h-[112px] min-w-[268px] sm:block" /></> : favoriteMatches.length > 0 ? favoriteMatches.map((match) => <MatchCard key={match.id} match={match} isFavorite onToggleFavorite={toggleFavorite} compact />) : <FavoriteEmpty />}</div></section>

    <section className="mt-8 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="inline-flex items-center gap-2 border-2 border-[#151515] bg-[#91e0ff] px-2 py-1 text-[10px] font-black uppercase tracking-[.14em]"><Trophy size={12} strokeWidth={3} />The main board</p><h2 className="display mt-2 text-5xl font-black uppercase leading-none">Today&apos;s <span className="text-[#e8462f]">action</span></h2></div><div className="flex items-center gap-3"><span className="hidden text-xs font-bold text-[#625c54] sm:inline">Refreshed {feed.data ? "just now" : "—"}</span><button onClick={() => feed.refetch()} className="nb-button px-3 py-2 text-xs uppercase"><Zap size={14} strokeWidth={3} />Refresh</button></div></section>

    <section className="scrollbar-none mt-5 flex gap-2 overflow-x-auto pb-2" aria-label="Sport filters">{sports.map((item) => <button key={item.id} onClick={() => setSport(item.id)} className={`flex shrink-0 items-center gap-2 border-[3px] border-[#151515] px-3 py-2 text-xs font-black uppercase shadow-[3px_3px_0_#151515] ${sport === item.id ? "bg-[#1857f6] text-white" : "bg-[#fffdf8] hover:bg-[#91e0ff]"}`}><span className={`grid h-5 min-w-5 place-items-center border border-[#151515] text-[8px] ${sport === item.id ? "bg-[#ffe24a] text-[#151515]" : "bg-[#f4f0e5]"}`}>{item.glyph}</span>{item.label}</button>)}</section>

    <section className="mt-6 flex flex-col gap-3 border-b-[3px] border-[#151515] pb-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-2 overflow-x-auto">{stateTabs.map((tab) => <button key={tab.id} onClick={() => setState(tab.id)} className={`whitespace-nowrap border-[3px] border-[#151515] px-4 py-2 text-xs font-black uppercase shadow-[3px_3px_0_#151515] ${state === tab.id ? "bg-[#ff6b4a]" : "bg-[#fffdf8] hover:bg-[#ffe24a]"}`}>{tab.id === "live" && <span className="mr-1.5 inline-block h-2 w-2 animate-pulse rounded-full bg-[#e8462f]" />}{tab.label}</button>)}</div><div className="flex items-center gap-3"><label className="flex h-10 flex-1 items-center gap-2 border-[3px] border-[#151515] bg-white px-3 lg:hidden"><Search size={15} strokeWidth={3} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search score center" className="min-w-0 flex-1 bg-transparent text-sm font-semibold outline-none placeholder:text-[#625c54]" /></label><button className="hidden items-center gap-2 border-[3px] border-[#151515] bg-[#fffdf8] px-3 py-2 text-xs font-black uppercase sm:flex"><CalendarDays size={14} strokeWidth={3} />Today <ChevronRight size={13} strokeWidth={3} /></button></div></section>

    <section className="mt-6"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><p className="display text-3xl font-black uppercase">{hasSearch ? `Results: “${search.trim()}”` : state === "live" ? "Live matches" : state === "upcoming" ? "Coming next" : "Final whistle"} {feed.data && <span className="align-middle border-2 border-[#151515] bg-[#ffe24a] px-2 py-1 text-sm">{feed.data.matches.length}</span>}</p><span className="border-2 border-[#151515] bg-white px-2 py-1 text-[9px] font-black uppercase tracking-[.1em]">{hasSearch ? "All match states" : "Refreshes every 45 sec"}</span></div>{feed.isLoading ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3"><MatchCardSkeleton /><MatchCardSkeleton /><MatchCardSkeleton /></div> : feed.isError ? <FeedError onRetry={() => feed.refetch()} /> : (feed.data?.matches.length ?? 0) === 0 ? <FeedEmpty label={pageLabel} /> : <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{feed.data?.matches.map((match, index) => <div key={match.id} className="nb-enter" style={{ animationDelay: `${index * 35}ms` }}><MatchCard match={match} isFavorite={favoriteIds.includes(match.id)} onToggleFavorite={toggleFavorite} /></div>)}</div>}</section>
    {feed.data && <section className="mt-9 border-[3px] border-[#151515] bg-[#91e0ff] px-4 py-4 shadow-[5px_5px_0_#151515]"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><p className="text-xs font-bold leading-5">League tables and fixture detail are wired to the <b className="uppercase">{feed.data.provider}</b> provider adapter. No API secrets reach the browser.</p><div className="scrollbar-none flex gap-2 overflow-x-auto">{feed.data.leagues.slice(0, 4).map((league) => <Link key={league.id} href={`/league/${league.id}`} className="shrink-0 border-2 border-[#151515] bg-white px-2.5 py-1.5 text-[10px] font-black uppercase hover:bg-[#ffe24a]">{league.name}</Link>)}</div></div></section>}
  </main><footer className="mt-4 border-t-[3px] border-[#151515] bg-[#151515] px-4 py-6 text-center text-[10px] font-bold uppercase tracking-[.12em] text-[#fffdf8]">Matchday · Secure server-side sports data adapter · Preview score data</footer></SportsAppLayout>;
}
