import type { StandingRow } from "@shared/sports";
import { FeedError } from "@/components/sports/ViewStates";
import { SportsAppLayout } from "@/components/SportsAppLayout";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, BarChart3, CalendarDays, ChevronRight, CircleDot, ShieldCheck, Trophy } from "lucide-react";
import { Link, useRoute } from "wouter";

function LeagueSkeleton() { return <main className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8"><div className="nb-skeleton h-8 w-32" /><div className="nb-skeleton mt-5 h-40 shadow-[6px_6px_0_#151515]" /><div className="nb-skeleton mt-5 h-72 shadow-[6px_6px_0_#151515]" /></main>; }

export default function League() {
  const [, params] = useRoute("/league/:leagueId");
  const leagueId = params?.leagueId ?? "";
  const league = trpc.sports.league.useQuery({ id: leagueId || "unavailable" }, { enabled: Boolean(leagueId) });
  const standings = trpc.sports.standings.useQuery({ leagueId: leagueId || "unavailable" }, { enabled: Boolean(leagueId) });
  const feed = trpc.sports.feed.useQuery({ leagueId: leagueId || "unavailable" }, { enabled: Boolean(leagueId), refetchInterval: 45_000 });
  if (league.isLoading || standings.isLoading || feed.isLoading) return <SportsAppLayout><LeagueSkeleton /></SportsAppLayout>;
  if (league.isError || standings.isError || feed.isError) return <SportsAppLayout><main className="mx-auto max-w-xl px-4 py-20"><FeedError onRetry={() => { league.refetch(); standings.refetch(); feed.refetch(); }} /></main></SportsAppLayout>;
  if (!league.data) return <SportsAppLayout><main className="mx-auto max-w-xl px-4 py-24 text-center"><CircleDot className="mx-auto" size={26} strokeWidth={3} /><h1 className="display mt-4 text-4xl font-black uppercase">League unavailable</h1><p className="mt-2 text-sm font-medium text-[#625c54]">This competition is not in the current feed.</p><Link href="/" className="nb-button mt-6 px-4 py-2.5 text-sm uppercase"><ArrowLeft size={15} strokeWidth={3} />All scores</Link></main></SportsAppLayout>;
  const info = league.data;
  return <SportsAppLayout><main className="mx-auto max-w-5xl px-4 pb-12 pt-6 sm:px-6 lg:px-8"><Link href="/" className="nb-button px-3 py-2 text-xs uppercase"><ArrowLeft size={15} strokeWidth={3} />All scores</Link>
    <section className="nb-shadow-lg relative mt-6 overflow-hidden border-[3px] border-[#151515] bg-[#ff6b4a] px-5 py-7 pr-20 sm:px-8 sm:pr-8"><div className="absolute right-0 top-0 h-full w-16 bg-[repeating-linear-gradient(45deg,#151515_0_12px,#ffe24a_12px_24px)]" /><div className="relative z-10 flex flex-col gap-5 sm:flex-row sm:items-center"><span className="grid h-16 w-16 place-items-center border-[3px] border-[#151515] bg-white text-2xl font-black shadow-[4px_4px_0_#151515]" style={{ color: info.badgeColor }}>{info.name.slice(0, 1)}</span><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.15em]"><Trophy size={13} strokeWidth={3} />{info.country}</div><h1 className="display mt-1 text-4xl font-black uppercase leading-none sm:text-5xl">{info.name}</h1><p className="mt-2 text-sm font-bold">{info.season} season · Results, fixtures, and league table</p></div><span className="border-[3px] border-[#151515] bg-[#ffe24a] px-3 py-2 text-[9px] font-black uppercase tracking-[.12em] sm:ml-auto"><ShieldCheck className="mr-1 inline" size={13} strokeWidth={3} />Verified feed</span></div></section>
    <section className="mt-6 grid gap-6 lg:grid-cols-[1.4fr_.6fr]"><div className="nb-card p-4 sm:p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.15em] text-[#1857f6]">Season overview</p><h2 className="display text-3xl font-black uppercase">Standings</h2></div><BarChart3 size={22} strokeWidth={3} /></div>{standings.data && standings.data.length > 0 ? <StandingsTable standings={standings.data} /> : <div className="mt-4 border-[3px] border-dashed border-[#151515] bg-[#f4f0e5] px-5 py-12 text-center"><BarChart3 className="mx-auto" strokeWidth={3} /><p className="mt-3 text-sm font-black uppercase">No table yet</p><p className="mx-auto mt-1 max-w-sm text-sm font-medium leading-6 text-[#625c54]">The provider has not supplied standings for this competition yet.</p></div>}</div><aside className="nb-card bg-[#ffe24a] p-5"><p className="text-[10px] font-black uppercase tracking-[.15em]">Competition</p><h2 className="display mt-1 text-3xl font-black uppercase">At a glance</h2><div className="mt-5 space-y-3"><InfoBlock label="Sport" value={info.sport.replace("-", " ")} /><InfoBlock label="Season" value={info.season} /><InfoBlock label="Matches in feed" value={String(feed.data?.matches.length ?? 0)} /></div></aside></section>
    <section className="nb-card mt-6 p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.15em] text-[#1857f6]">From the score center</p><h2 className="display mt-1 text-3xl font-black uppercase">Fixtures & results</h2></div><CalendarDays size={22} strokeWidth={3} /></div>{(feed.data?.matches.length ?? 0) > 0 ? <div className="mt-4 border-t-[3px] border-[#151515]">{feed.data?.matches.map((match) => <Link key={match.id} href={`/match/${match.id}`} className="grid grid-cols-[1fr_auto_1fr_auto] items-center gap-3 border-b-2 border-[#151515] bg-white py-3.5 text-sm hover:bg-[#91e0ff]"><span className="truncate text-right font-black">{match.homeTeam.name}</span><span className="grid h-7 w-7 place-items-center border-2 border-[#151515] text-[8px] font-black text-white" style={{ background: match.homeTeam.badgeColor }}>{match.homeTeam.shortName}</span><span className="display text-xl font-black">{match.score.home}–{match.score.away}</span><span className="flex items-center gap-2 text-[10px] font-black uppercase"><span>{match.statusDetail}</span><ChevronRight size={14} strokeWidth={3} /></span></Link>)}</div> : <p className="mt-4 border-[3px] border-dashed border-[#151515] bg-[#f4f0e5] px-4 py-8 text-center text-sm font-bold">No fixtures are currently available for this league.</p>}</section>
  </main></SportsAppLayout>;
}

function InfoBlock({ label, value }: { label: string; value: string }) { return <div className="border-2 border-[#151515] bg-white p-3"><span className="text-[9px] font-black uppercase tracking-[.12em]">{label}</span><p className="mt-1 capitalize text-sm font-black">{value}</p></div>; }
function StandingsTable({ standings }: { standings: StandingRow[] }) { return <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[590px] text-left"><thead><tr className="border-b-[3px] border-[#151515] bg-[#91e0ff] text-[9px] font-black uppercase tracking-[.12em]"><th className="px-2 py-3">#</th><th className="py-3">Team</th><th className="py-3 text-center">P</th><th className="py-3 text-center">W</th><th className="py-3 text-center">D</th><th className="py-3 text-center">L</th><th className="py-3 text-center">GD</th><th className="py-3 text-right">Pts</th><th className="px-2 py-3 text-right">Form</th></tr></thead><tbody>{standings.map((row) => <tr key={row.team.id} className="border-b-2 border-[#151515] bg-white last:border-b-0 hover:bg-[#fff3bb]"><td className="px-2 py-3 text-sm font-black">{row.rank}</td><td className="py-3"><span className="flex items-center gap-2.5"><span className="grid h-7 w-7 place-items-center border-2 border-[#151515] text-[8px] font-black text-white" style={{ background: row.team.badgeColor }}>{row.team.shortName}</span><span className="text-sm font-black">{row.team.name}</span></span></td><td className="py-3 text-center text-sm font-bold">{row.played}</td><td className="py-3 text-center text-sm font-bold">{row.won}</td><td className="py-3 text-center text-sm font-bold">{row.drawn}</td><td className="py-3 text-center text-sm font-bold">{row.lost}</td><td className="py-3 text-center text-sm font-bold">{row.goalDifference ?? "—"}</td><td className="py-3 text-right text-sm font-black">{row.points}</td><td className="px-2 py-3"><span className="flex justify-end gap-1">{row.form?.map((result, index) => <span key={`${result}-${index}`} className={`grid h-5 w-5 place-items-center border border-[#151515] text-[9px] font-black ${result === "W" ? "bg-[#bfff5d]" : result === "D" ? "bg-[#e5dfd1]" : "bg-[#ff6b4a]"}`}>{result}</span>)}</span></td></tr>)}</tbody></table></div>; }
