import type { StandingRow } from "@shared/sports";
import { FeedError } from "@/components/sports/ViewStates";
import { SportsAppLayout } from "@/components/SportsAppLayout";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, BarChart3, CalendarDays, ChevronRight, CircleDot, ShieldCheck, Trophy } from "lucide-react";
import { Link, useRoute } from "wouter";

function LeagueSkeleton() { return <main className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8"><div className="h-4 w-32 animate-pulse rounded bg-[#29434a]" /><div className="mt-5 h-36 animate-pulse rounded-[26px] border border-[#29434a] bg-[#102228]" /><div className="mt-5 h-72 animate-pulse rounded-2xl border border-[#29434a] bg-[#102228]" /></main>; }

export default function League() {
  const [, params] = useRoute("/league/:leagueId");
  const leagueId = params?.leagueId ?? "";
  const league = trpc.sports.league.useQuery({ id: leagueId || "unavailable" }, { enabled: Boolean(leagueId) });
  const standings = trpc.sports.standings.useQuery({ leagueId: leagueId || "unavailable" }, { enabled: Boolean(leagueId) });
  const feed = trpc.sports.feed.useQuery({ leagueId: leagueId || "unavailable" }, { enabled: Boolean(leagueId), refetchInterval: 45_000 });
  if (league.isLoading || standings.isLoading || feed.isLoading) return <SportsAppLayout><LeagueSkeleton /></SportsAppLayout>;
  if (league.isError || standings.isError || feed.isError) return <SportsAppLayout><main className="mx-auto max-w-xl px-4 py-20"><FeedError onRetry={() => { league.refetch(); standings.refetch(); feed.refetch(); }} /></main></SportsAppLayout>;
  if (!league.data) return <SportsAppLayout><main className="mx-auto max-w-xl px-4 py-24 text-center"><CircleDot className="mx-auto text-[#91b1b3]" /><h1 className="display mt-4 text-3xl font-bold uppercase text-white">League unavailable</h1><p className="mt-2 text-sm text-[#8aa5a8]">This competition is not in the current feed.</p><Link href="/" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#a6ff00] px-4 py-2.5 text-sm font-bold text-[#16281b]"><ArrowLeft size={15} />All scores</Link></main></SportsAppLayout>;
  const info = league.data;
  return <SportsAppLayout>
    <main className="mx-auto max-w-5xl px-4 pb-12 pt-6 sm:px-6 lg:px-8"><Link href="/" className="inline-flex items-center gap-2 rounded-xl border border-[#2d4a50] bg-[#10242a] px-3 py-2 text-xs font-bold text-[#cfe0e0] hover:border-[#4c6f76]"><ArrowLeft size={15} />All scores</Link>
      <section className="relative mt-5 overflow-hidden rounded-[27px] border border-[#35575e] bg-[linear-gradient(115deg,#142e33,#102329)] px-5 py-6 sm:px-8"><div className="absolute -right-10 -top-10 h-44 w-44 rounded-full border-[24px] border-white/5" /><div className="relative flex flex-col gap-5 sm:flex-row sm:items-center"><span className="grid h-16 w-16 place-items-center rounded-[20px] text-2xl font-extrabold text-white shadow-lg" style={{ background: info.badgeColor }}>{info.name.slice(0, 1)}</span><div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.15em] text-[#aec5c6]"><Trophy size={13} className="text-[#b9ff50]" />{info.country}</div><h1 className="display mt-1 text-4xl font-bold uppercase tracking-wide text-white">{info.name}</h1><p className="mt-1 text-sm text-[#8ea9ac]">{info.season} season · Results, fixtures, and league table</p></div><div className="sm:ml-auto"><span className="inline-flex items-center gap-1.5 rounded-full bg-[#a6ff00]/12 px-3 py-2 text-[10px] font-bold uppercase tracking-[0.12em] text-[#c9ff81]"><ShieldCheck size={13} />Verified feed</span></div></div></section>
      <section className="mt-5 grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><div className="rounded-2xl border border-[#2c484e] bg-[#10242a]/90 p-4 sm:p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#8da7aa]">Season overview</p><h2 className="display text-2xl font-bold uppercase tracking-wide text-white">Standings</h2></div><BarChart3 size={19} className="text-[#baff50]" /></div>{standings.data && standings.data.length > 0 ? <StandingsTable standings={standings.data} /> : <div className="mt-4 rounded-xl border border-dashed border-[#36535a] px-5 py-12 text-center"><BarChart3 className="mx-auto text-[#789397]" /><p className="mt-3 text-sm font-bold text-white">Standings are not available yet</p><p className="mx-auto mt-1 max-w-sm text-sm leading-6 text-[#88a3a5]">This provider adapter has not supplied a league table for this competition. The page will populate automatically when it does.</p></div>}</div>
        <aside className="rounded-2xl border border-[#2c484e] bg-[#10242a]/90 p-5"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#8da7aa]">Competition</p><h2 className="display mt-1 text-2xl font-bold uppercase tracking-wide text-white">At a glance</h2><div className="mt-5 space-y-3"><div className="rounded-xl bg-[#1a3439] p-3"><span className="text-[10px] font-bold uppercase tracking-[0.13em] text-[#87a1a4]">Sport</span><p className="mt-1 capitalize text-sm font-bold text-white">{info.sport.replace("-", " ")}</p></div><div className="rounded-xl bg-[#1a3439] p-3"><span className="text-[10px] font-bold uppercase tracking-[0.13em] text-[#87a1a4]">Season</span><p className="mt-1 text-sm font-bold text-white">{info.season}</p></div><div className="rounded-xl bg-[#1a3439] p-3"><span className="text-[10px] font-bold uppercase tracking-[0.13em] text-[#87a1a4]">Matches in feed</span><p className="mt-1 text-sm font-bold text-[#caff7b]">{feed.data?.matches.length ?? 0}</p></div></div></aside></section>
      <section className="mt-5 rounded-2xl border border-[#2c484e] bg-[#10242a]/90 p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#8da7aa]">From the score center</p><h2 className="display mt-1 text-2xl font-bold uppercase tracking-wide text-white">Fixtures & results</h2></div><CalendarDays size={19} className="text-[#baff50]" /></div>{(feed.data?.matches.length ?? 0) > 0 ? <div className="mt-4 divide-y divide-[#2b464d]">{feed.data?.matches.map((match) => <Link key={match.id} href={`/match/${match.id}`} className="grid grid-cols-[1fr_auto_1fr_auto] items-center gap-3 py-3.5 text-sm hover:bg-[#173137]/50"><span className="truncate text-right font-bold text-white">{match.homeTeam.name}</span><span className="grid h-7 w-7 place-items-center rounded-lg text-[9px] font-bold text-white" style={{ background: match.homeTeam.badgeColor }}>{match.homeTeam.shortName}</span><span className="display text-lg font-bold text-[#dfffa6]">{match.score.home}–{match.score.away}</span><span className="flex items-center gap-2 text-[11px] font-bold text-[#90aaad]"><span>{match.statusDetail}</span><ChevronRight size={14} /></span></Link>)}</div> : <p className="mt-4 rounded-xl border border-dashed border-[#36535a] px-4 py-8 text-center text-sm text-[#8ca5a8]">No fixtures are currently available for this league.</p>}</section>
    </main>
  </SportsAppLayout>;
}

function StandingsTable({ standings }: { standings: StandingRow[] }) { return <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[590px] text-left"><thead><tr className="border-b border-[#2d484e] text-[10px] font-bold uppercase tracking-[0.12em] text-[#829da0]"><th className="pb-3 pl-2">#</th><th className="pb-3">Team</th><th className="pb-3 text-center">P</th><th className="pb-3 text-center">W</th><th className="pb-3 text-center">D</th><th className="pb-3 text-center">L</th><th className="pb-3 text-center">GD</th><th className="pb-3 text-right">Pts</th><th className="pb-3 pl-4 text-right">Form</th></tr></thead><tbody>{standings.map((row) => <tr key={row.team.id} className="border-b border-[#27434a] last:border-0"><td className="py-3 pl-2 text-sm font-bold text-[#9db6b8]">{row.rank}</td><td className="py-3"><span className="flex items-center gap-2.5"><span className="grid h-7 w-7 place-items-center rounded-lg text-[8px] font-bold text-white" style={{ background: row.team.badgeColor }}>{row.team.shortName}</span><span className="text-sm font-bold text-white">{row.team.name}</span></span></td><td className="py-3 text-center text-sm text-[#b3c8c9]">{row.played}</td><td className="py-3 text-center text-sm text-[#b3c8c9]">{row.won}</td><td className="py-3 text-center text-sm text-[#b3c8c9]">{row.drawn}</td><td className="py-3 text-center text-sm text-[#b3c8c9]">{row.lost}</td><td className="py-3 text-center text-sm text-[#b3c8c9]">{row.goalDifference ?? "—"}</td><td className="py-3 text-right text-sm font-extrabold text-[#d9ff9d]">{row.points}</td><td className="py-3 pl-4"><span className="flex justify-end gap-1">{row.form?.map((result, index) => <span key={`${result}-${index}`} className={`grid h-5 w-5 place-items-center rounded text-[9px] font-bold ${result === "W" ? "bg-[#a6ff00]/14 text-[#c8ff79]" : result === "D" ? "bg-[#667d81]/25 text-[#c1d3d4]" : "bg-[#ff735f]/14 text-[#ff9d8d]"}`}>{result}</span>)}</span></td></tr>)}</tbody></table></div>; }
