import type { MatchEvent, SportsMatch } from "@shared/sports";
import { FeedError } from "@/components/sports/ViewStates";
import { SportsAppLayout } from "@/components/SportsAppLayout";
import { useFavoriteMatches } from "@/hooks/useFavoriteMatches";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CircleDot, ClipboardList, Clock3, Heart, MapPin, Radio, Share2, ShieldCheck, Users } from "lucide-react";
import { useState } from "react";
import { Link, useRoute } from "wouter";

type DetailTab = "summary" | "lineups";

function Crest({ match, side }: { match: SportsMatch; side: "home" | "away" }) {
  const team = side === "home" ? match.homeTeam : match.awayTeam;
  return <div className="flex flex-col items-center gap-3 text-center"><span className="grid h-20 w-20 place-items-center rounded-[24px] border border-white/15 text-xl font-extrabold text-white shadow-[0_12px_30px_rgba(0,0,0,0.22)] sm:h-24 sm:w-24" style={{ background: `linear-gradient(145deg, ${team.badgeColor}, #10262b)` }}>{team.shortName}</span><span className="max-w-[125px] text-sm font-bold leading-tight text-white sm:text-base">{team.name}</span>{team.record && <span className="text-[11px] text-[#85a0a4]">{team.record}</span>}</div>;
}

function EventIcon({ kind }: { kind: MatchEvent["kind"] }) {
  const colors: Record<MatchEvent["kind"], string> = { goal: "bg-[#a6ff00] text-[#19320c]", "yellow-card": "bg-[#ffd447] text-[#3c2e00]", "red-card": "bg-[#ff6e6e] text-[#3a0808]", substitution: "bg-[#5ad5ff] text-[#07394a]", try: "bg-[#b8ff44] text-[#17300a]", penalty: "bg-[#f8b550] text-[#3e2500]", wicket: "bg-[#e9d767] text-[#363000]", ace: "bg-[#7ac9ff] text-[#0b3654]", basket: "bg-[#ff9569] text-[#4d1309]", period: "bg-[#9bb4b7] text-[#142a30]" };
  const labels: Record<MatchEvent["kind"], string> = { goal: "G", "yellow-card": "Y", "red-card": "R", substitution: "↔", try: "T", penalty: "P", wicket: "W", ace: "A", basket: "2", period: "•" };
  return <span className={`grid h-7 w-7 place-items-center rounded-full text-[10px] font-extrabold ${colors[kind]}`}>{labels[kind]}</span>;
}

function DetailSkeleton() {
  return <main className="mx-auto w-full max-w-5xl px-4 py-8 sm:px-6 lg:px-8"><div className="h-4 w-32 animate-pulse rounded bg-[#29434a]" /><div className="mt-5 h-[300px] animate-pulse rounded-[26px] border border-[#29434a] bg-[#102228]" /><div className="mt-5 h-48 animate-pulse rounded-2xl border border-[#29434a] bg-[#102228]" /></main>;
}

function MatchNotFound() { return <main className="mx-auto w-full max-w-xl px-4 py-24 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#243e43] text-[#a9c5c6]"><CircleDot size={22} /></span><h1 className="display mt-5 text-3xl font-bold uppercase text-white">Match unavailable</h1><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#8ca5a8]">This match is not in the current feed. It may have been removed or its fixture ID may have changed.</p><Link href="/" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#a6ff00] px-4 py-2.5 text-sm font-bold text-[#16281b]"><ArrowLeft size={15} />Return to scores</Link></main>; }

export default function MatchDetails() {
  const [, params] = useRoute("/match/:matchId");
  const matchId = params?.matchId ?? "";
  const result = trpc.sports.match.useQuery({ id: matchId || "unavailable" }, { enabled: Boolean(matchId), refetchInterval: 45_000 });
  const [tab, setTab] = useState<DetailTab>("summary");
  const { favoriteIds, toggleFavorite } = useFavoriteMatches();

  if (result.isLoading) return <SportsAppLayout><DetailSkeleton /></SportsAppLayout>;
  if (result.isError) return <SportsAppLayout><main className="mx-auto max-w-xl px-4 py-20"><FeedError onRetry={() => result.refetch()} /></main></SportsAppLayout>;
  if (!result.data) return <SportsAppLayout><MatchNotFound /></SportsAppLayout>;
  const match = result.data;
  const isFavorite = favoriteIds.includes(match.id);

  return <SportsAppLayout>
    <main className="mx-auto w-full max-w-5xl px-4 pb-12 pt-6 sm:px-6 lg:px-8">
      <div className="flex items-center justify-between gap-3"><Link href="/" className="inline-flex items-center gap-2 rounded-xl border border-[#2d4a50] bg-[#10242a] px-3 py-2 text-xs font-bold text-[#cfe0e0] hover:border-[#4c6f76]"><ArrowLeft size={15} />All scores</Link><div className="flex gap-2"><button onClick={() => toggleFavorite(match.id)} className={`grid h-9 w-9 place-items-center rounded-xl border ${isFavorite ? "border-[#a6ff00]/40 bg-[#a6ff00]/12 text-[#bfff55]" : "border-[#2d4a50] bg-[#10242a] text-[#b2c8ca]"}`} aria-label="Toggle favorite"><Heart size={16} fill={isFavorite ? "currentColor" : "none"} /></button><button className="grid h-9 w-9 place-items-center rounded-xl border border-[#2d4a50] bg-[#10242a] text-[#b2c8ca]" aria-label="Share match"><Share2 size={16} /></button></div></div>

      <section className="relative mt-5 overflow-hidden rounded-[28px] border border-[#35575e] bg-[linear-gradient(125deg,#142f33,#102328_48%,#14291e)] px-5 py-7 shadow-[0_20px_65px_rgba(0,0,0,0.24)] sm:px-10 sm:py-9"><div className="absolute left-[11%] top-0 h-full w-px bg-[#a6ff00]/10" /><div className="absolute right-[11%] top-0 h-full w-px bg-[#a6ff00]/10" />
        <div className="relative flex items-center justify-center gap-2 text-center text-[11px] font-bold uppercase tracking-[0.12em] text-[#acbec0]"><span className="grid h-5 w-5 place-items-center rounded-md text-[8px] text-white" style={{ background: match.leagueBadgeColor }}>{match.leagueName[0]}</span><Link href={`/league/${match.leagueId}`} className="hover:text-[#caff7b]">{match.leagueName}</Link><span className="text-[#607c80]">·</span><span>{match.round ?? "Match center"}</span></div>
        <div className="relative mx-auto mt-6 grid max-w-3xl grid-cols-[1fr_auto_1fr] items-center gap-4 sm:gap-9"><Crest match={match} side="home" /><div className="min-w-[82px] text-center"><span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.13em] ${match.status === "live" ? "bg-[#a6ff00]/12 text-[#caff7b]" : "bg-[#e8f0ef]/8 text-[#b1c6c7]"}`}>{match.status === "live" && <Radio size={10} />}{match.statusDetail}</span><div className="display mt-3 whitespace-nowrap text-5xl font-bold leading-none text-white sm:text-6xl"><span>{match.score.home}</span><span className="mx-1.5 text-[#6c8a8e]">–</span><span>{match.score.away}</span></div><span className="mt-3 block text-[11px] text-[#86a1a4]">{new Date(match.startTime).toLocaleString(undefined, { weekday: "short", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })}</span></div><Crest match={match} side="away" /></div>
        <div className="relative mt-7 flex flex-wrap items-center justify-center gap-x-4 gap-y-2 text-[11px] text-[#93adaf]"><span className="flex items-center gap-1.5"><MapPin size={13} className="text-[#b7ff4e]" />{match.venue ?? "Venue TBC"}</span><span className="hidden h-3 w-px bg-[#47646a] sm:block" /><span className="flex items-center gap-1.5"><Clock3 size={13} className="text-[#b7ff4e]" />{match.status === "live" ? "Updating live" : match.status === "finished" ? "Full time" : "Fixture confirmed"}</span></div>
      </section>

      <div className="mt-5 flex gap-1 rounded-xl border border-[#2d484f] bg-[#0c1d22] p-1"><button onClick={() => setTab("summary")} className={`flex flex-1 items-center justify-center gap-2 rounded-lg px-3 py-2.5 text-xs font-bold ${tab === "summary" ? "bg-[#29474c] text-white" : "text-[#829da0] hover:text-white"}`}><ClipboardList size={14} />Summary</button><button onClick={() => setTab("lineups")} className={`flex flex-1 items-center justify-center gap-2 rounded-lg px-3 py-2.5 text-xs font-bold ${tab === "lineups" ? "bg-[#29474c] text-white" : "text-[#829da0] hover:text-white"}`}><Users size={14} />Lineups</button></div>

      {tab === "summary" ? <div className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><section className="rounded-2xl border border-[#2c484e] bg-[#10242a]/90 p-5"><h2 className="display text-2xl font-bold uppercase tracking-wide text-white">Score breakdown</h2>{match.scoreSegments.length > 0 ? <div className="mt-4 overflow-hidden rounded-xl border border-[#2b474d]"><div className="grid grid-cols-[1fr_auto_1fr] border-b border-[#2b474d] bg-[#19343a] px-4 py-2 text-[10px] font-bold uppercase tracking-[0.13em] text-[#90aaad]"><span>{match.homeTeam.shortName}</span><span>Period</span><span className="text-right">{match.awayTeam.shortName}</span></div>{match.scoreSegments.map((segment) => <div key={segment.label} className={`grid grid-cols-[1fr_auto_1fr] px-4 py-3 text-sm ${segment.active ? "bg-[#a6ff00]/8" : ""}`}><span className="font-bold text-white">{segment.home}</span><span className={`text-xs font-semibold ${segment.active ? "text-[#caff78]" : "text-[#88a2a5]"}`}>{segment.label}</span><span className="text-right font-bold text-white">{segment.away}</span></div>)}</div> : <p className="mt-4 rounded-xl border border-dashed border-[#36535a] px-4 py-8 text-center text-sm text-[#8ca5a8]">Period-by-period scoring will appear once the match starts.</p>}</section>
        <section className="rounded-2xl border border-[#2c484e] bg-[#10242a]/90 p-5"><h2 className="display text-2xl font-bold uppercase tracking-wide text-white">Match status</h2><div className="mt-4 space-y-3"><div className="rounded-xl bg-[#1a3439] p-3"><span className="text-[10px] font-bold uppercase tracking-[0.13em] text-[#86a2a5]">Competition</span><p className="mt-1 text-sm font-bold text-white">{match.leagueName}</p></div><div className="rounded-xl bg-[#1a3439] p-3"><span className="text-[10px] font-bold uppercase tracking-[0.13em] text-[#86a2a5]">Status</span><p className="mt-1 text-sm font-bold text-[#c9ff85]">{match.statusDetail}</p></div><div className="rounded-xl bg-[#1a3439] p-3"><span className="text-[10px] font-bold uppercase tracking-[0.13em] text-[#86a2a5]">Data protection</span><p className="mt-1 flex items-center gap-1.5 text-sm font-bold text-white"><ShieldCheck size={15} className="text-[#b7ff4d]" />Server-side provider</p></div></div></section>
        <section className="rounded-2xl border border-[#2c484e] bg-[#10242a]/90 p-5 lg:col-span-2"><div className="flex items-center justify-between"><h2 className="display text-2xl font-bold uppercase tracking-wide text-white">Match events</h2><span className="rounded-full bg-[#203c41] px-2 py-1 text-[10px] font-bold text-[#a9c0c2]">{match.events.length}</span></div>{match.events.length > 0 ? <ol className="mt-5 divide-y divide-[#29454b]">{match.events.map((event) => <li key={event.id} className={`grid grid-cols-[44px_1fr_1fr] items-center gap-3 py-3 ${event.team === "away" ? "text-right" : ""}`}><span className="text-[11px] font-bold text-[#8aa5a8]">{event.minute}</span><div className={`${event.team === "home" ? "col-start-2" : "col-start-3"} flex items-center gap-2 ${event.team === "away" ? "flex-row-reverse" : ""}`}><EventIcon kind={event.kind} /><span><span className="block text-sm font-bold text-white">{event.title}</span>{event.detail && <span className="block text-[11px] text-[#89a4a7]">{event.detail}</span>}</span></div></li>)}</ol> : <p className="mt-4 rounded-xl border border-dashed border-[#36535a] px-4 py-8 text-center text-sm text-[#8ca5a8]">No match events have been recorded yet.</p>}</section>
      </div> : <section className="mt-5 rounded-2xl border border-[#2c484e] bg-[#10242a]/90 p-5"><h2 className="display text-2xl font-bold uppercase tracking-wide text-white">Starting lineups</h2>{match.homeLineup && match.awayLineup ? <div className="mt-5 grid gap-5 md:grid-cols-2"><Lineup teamName={match.homeTeam.name} players={match.homeLineup} color={match.homeTeam.badgeColor} /><Lineup teamName={match.awayTeam.name} players={match.awayLineup} color={match.awayTeam.badgeColor} /></div> : <div className="mt-4 rounded-xl border border-dashed border-[#36535a] px-5 py-12 text-center"><Users className="mx-auto text-[#789397]" /><p className="mt-3 text-sm font-bold text-white">Lineups have not been announced</p><p className="mt-1 text-sm text-[#88a3a5]">We will show verified starters as soon as the provider has them.</p></div>}</section>}
    </main>
  </SportsAppLayout>;
}

function Lineup({ teamName, players, color }: { teamName: string; players: NonNullable<SportsMatch["homeLineup"]>; color: string }) { return <div className="overflow-hidden rounded-xl border border-[#2d4b51]"><div className="flex items-center gap-2 border-b border-[#2d4b51] bg-[#19343a] px-3 py-3"><span className="h-3 w-3 rounded-full" style={{ background: color }} /><h3 className="text-sm font-bold text-white">{teamName}</h3></div><ol>{players.map((player) => <li key={player.number} className="flex items-center gap-3 border-b border-[#274349] px-3 py-2.5 last:border-0"><span className="grid h-6 w-6 place-items-center rounded-md bg-[#213e44] text-[10px] font-bold text-[#b9d1d3]">{player.number}</span><span className="flex-1 text-sm font-semibold text-[#eff8f3]">{player.name}{player.captain && <span className="ml-1.5 text-[10px] text-[#caff7a]">(C)</span>}</span><span className="text-[10px] font-bold text-[#829da0]">{player.position}</span></li>)}</ol></div>; }
