import type { SportsMatch } from "@shared/sports";
import { Clock3, Heart, MapPin, Star } from "lucide-react";
import { Link } from "wouter";

type MatchCardProps = { match: SportsMatch; isFavorite: boolean; onToggleFavorite: (id: string) => void; compact?: boolean; };

function Crest({ name, shortName, color, size = "md" }: { name: string; shortName: string; color: string; size?: "sm" | "md" }) {
  return <span title={name} aria-label={`${name} crest`} className={`${size === "sm" ? "h-7 w-7 text-[8px]" : "h-10 w-10 text-[10px]"} grid shrink-0 place-items-center border-2 border-[#151515] font-black tracking-tight text-white shadow-[2px_2px_0_#151515]`} style={{ background: color }}>{shortName.slice(0, 3)}</span>;
}

function StatusPill({ match }: { match: SportsMatch }) {
  if (match.status === "live") return <span className="inline-flex items-center gap-1.5 border-2 border-[#151515] bg-[#ff6b4a] px-2 py-1 text-[9px] font-black uppercase tracking-[.12em]"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-[#151515]" />Live {match.statusDetail}</span>;
  if (match.status === "finished") return <span className="border-2 border-[#151515] bg-[#e8e1d2] px-2 py-1 text-[9px] font-black uppercase tracking-[.12em]">{match.statusDetail}</span>;
  return <span className="inline-flex items-center gap-1 border-2 border-[#151515] bg-[#91e0ff] px-2 py-1 text-[9px] font-black uppercase tracking-[.1em]"><Clock3 size={10} strokeWidth={3} />{match.statusDetail}</span>;
}

export function MatchCard({ match, isFavorite, onToggleFavorite, compact = false }: MatchCardProps) {
  return <article className={`group relative border-[3px] border-[#151515] bg-[#fffdf8] shadow-[5px_5px_0_#151515] transition-transform hover:-translate-y-1 ${compact ? "min-w-[268px]" : ""}`}>
    {match.status === "live" && <span className="absolute -left-[3px] -top-[3px] h-3 w-3 border-r-[3px] border-b-[3px] border-[#151515] bg-[#ffe24a]" />}
    <div className="flex items-center justify-between gap-3 border-b-[3px] border-[#151515] bg-[#e9f6ff] px-3 py-2.5"><Link href={`/league/${match.leagueId}`} className="flex min-w-0 items-center gap-2 hover:underline"><span className="grid h-5 w-5 shrink-0 place-items-center border border-[#151515] text-[8px] font-black text-white" style={{ background: match.leagueBadgeColor }}>{match.leagueName.slice(0, 1)}</span><span className="truncate text-[10px] font-black uppercase tracking-[.08em]">{match.leagueName}</span></Link><StatusPill match={match} /></div>
    <Link href={`/match/${match.id}`} className="block px-3 py-4"><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-2"><div className="flex min-w-0 items-center justify-end gap-2 text-right"><span className="min-w-0"><span className="block truncate text-sm font-black">{match.homeTeam.name}</span>{match.homeTeam.record && <span className="mt-0.5 block text-[10px] font-bold text-[#625c54]">{match.homeTeam.record}</span>}</span><Crest name={match.homeTeam.name} shortName={match.homeTeam.shortName} color={match.homeTeam.badgeColor} /></div><div className="min-w-[60px] text-center"><div className={`display text-[33px] font-black leading-none ${match.status === "live" ? "text-[#e43f28]" : "text-[#151515]"}`}>{match.score.home}<span className="mx-1 text-[#151515]">–</span>{match.score.away}</div>{match.status === "upcoming" && <span className="mt-1 block text-[9px] font-black uppercase text-[#1857f6]">{new Date(match.startTime).toLocaleDateString(undefined, { month: "short", day: "numeric" })}</span>}</div><div className="flex min-w-0 items-center gap-2"><Crest name={match.awayTeam.name} shortName={match.awayTeam.shortName} color={match.awayTeam.badgeColor} /><span className="min-w-0"><span className="block truncate text-sm font-black">{match.awayTeam.name}</span>{match.awayTeam.record && <span className="mt-0.5 block text-[10px] font-bold text-[#625c54]">{match.awayTeam.record}</span>}</span></div></div>{match.scoreSegments.length > 0 && <p className="mt-3 border-t-2 border-dashed border-[#151515] pt-2 text-center text-[9px] font-bold uppercase tracking-[.06em] text-[#625c54]">{match.scoreSegments.map((segment) => `${segment.label} ${segment.home}–${segment.away}`).join(" · ")}</p>}</Link>
    <div className="flex items-center justify-between border-t-[3px] border-[#151515] bg-[#fff3bb] px-3 py-2"><span className="flex min-w-0 items-center gap-1.5 text-[9px] font-black uppercase tracking-[.08em] text-[#514c43]">{match.venue ? <><MapPin size={11} strokeWidth={3} /><span className="truncate">{match.venue}</span></> : <span>{match.round ?? "Match center"}</span>}</span><button onClick={() => onToggleFavorite(match.id)} aria-label={isFavorite ? `Remove ${match.homeTeam.name} versus ${match.awayTeam.name} from favorites` : `Favorite ${match.homeTeam.name} versus ${match.awayTeam.name}`} className={`grid h-7 w-7 place-items-center border-2 border-[#151515] ${isFavorite ? "bg-[#ff6b4a]" : "bg-white hover:bg-[#ffe24a]"}`}><Heart size={14} strokeWidth={3} fill={isFavorite ? "currentColor" : "none"} /></button></div>
  </article>;
}

export function MatchCardSkeleton() { return <div className="nb-skeleton h-[202px] shadow-[5px_5px_0_#151515]" />; }
export function FavoriteEmpty() { return <div className="flex min-w-[250px] items-center gap-3 border-[3px] border-dashed border-[#151515] bg-[#fffdf8] px-4 py-3"><span className="grid h-9 w-9 place-items-center border-2 border-[#151515] bg-[#ffe24a]"><Star size={16} strokeWidth={3} /></span><span className="text-xs leading-snug">No pinned drama yet.<br /><b className="font-black">Hit a heart to park a match here.</b></span></div>; }
